# -*- coding: utf-8 -*-
"""Synthetic linear viscoelastic protocols for Boltzmann memory (R0/R1).

Ground-truth stress is generated by PronyBoltzmannKernel with known
{λ_k, G_k, G_∞} (isotropic) or {λ_k, A_k} (anisotropic).
"""

from __future__ import annotations

from typing import Optional

import numpy as np
import torch

from hnf.rheo_memory import PronyBoltzmannKernel

PROTOCOL_TO_ID = {
    "startup_shear": 0,
    "oscillatory": 1,
    "multi_step": 2,
}
ID_TO_PROTOCOL = {v: k for k, v in PROTOCOL_TO_ID.items()}


def _make_gt_kernel(
    *,
    n_modes: int,
    dim: int,
    anisotropic: bool,
    lambdas: list[float],
    weights: list[float] | np.ndarray,
    g_inf: float,
) -> PronyBoltzmannKernel:
    if anisotropic:
        # weights: length n_modes * dim (diagonal entries) or (n_modes, dim)
        w = np.asarray(weights, dtype=np.float64).reshape(n_modes, dim)
        k = PronyBoltzmannKernel(
            n_modes=n_modes,
            dim=dim,
            anisotropic=True,
            lambda_init=lambdas,
            g_init=[float(w[i].mean()) for i in range(n_modes)],
            g_inf_init=g_inf,
        )
        with torch.no_grad():
            L = torch.zeros(n_modes, dim, dim)
            for i in range(n_modes):
                L[i].diagonal().copy_(torch.tensor(np.sqrt(np.maximum(w[i], 1e-6))))
            k.diff_L.copy_(L)
        return k
    return PronyBoltzmannKernel(
        n_modes=n_modes,
        dim=dim,
        anisotropic=False,
        lambda_init=lambdas,
        g_init=list(weights),
        g_inf_init=g_inf,
    )


def make_protocol(
    name: str,
    *,
    n_steps: int,
    dt: float,
    rng: np.random.Generator,
    dim: int = 1,
) -> np.ndarray:
    """Return γ̇(t) as (T,) or (T, d)."""
    t = np.arange(n_steps, dtype=np.float64) * dt
    if name == "startup_shear":
        rate = float(rng.uniform(0.05, 0.5))
        gd = np.full(n_steps, rate, dtype=np.float64)
    elif name == "oscillatory":
        amp = float(rng.uniform(0.05, 0.4))
        omega = float(rng.uniform(0.2, 2.0))
        phase = float(rng.uniform(0.0, 2.0 * np.pi))
        # γ = amp sin(ωt+φ) → γ̇ = amp ω cos(ωt+φ)
        gd = amp * omega * np.cos(omega * t + phase)
    elif name == "multi_step":
        gd = np.zeros(n_steps, dtype=np.float64)
        n_seg = int(rng.integers(2, 5))
        cuts = np.sort(rng.choice(np.arange(1, n_steps), size=n_seg - 1, replace=False))
        bounds = np.concatenate([[0], cuts, [n_steps]])
        for a, b in zip(bounds[:-1], bounds[1:]):
            gd[a:b] = float(rng.uniform(-0.4, 0.4))
    else:
        raise ValueError(name)

    if dim == 1:
        return gd.astype(np.float32)
    # Anisotropic: independent / correlated channels
    out = np.zeros((n_steps, dim), dtype=np.float32)
    out[:, 0] = gd.astype(np.float32)
    for c in range(1, dim):
        scale = float(rng.uniform(0.3, 1.2))
        shift = int(rng.integers(0, max(1, n_steps // 8)))
        out[:, c] = scale * np.roll(gd, shift).astype(np.float32)
    return out


def make_rheo_sample(
    *,
    n_steps: int = 256,
    dt: float = 0.05,
    n_modes: int = 2,
    dim: int = 1,
    anisotropic: bool = False,
    protocol: Optional[str] = None,
    seed: int = 0,
    noise_std: float = 0.01,
    lambdas: Optional[list[float]] = None,
    weights: Optional[list[float] | np.ndarray] = None,
    g_inf: Optional[float] = None,
) -> dict:
    """One synthetic sample with GT Prony params and stress.

    If ``lambdas`` / ``weights`` are provided, use that fixed material
    (R0 identification: shared spectrum, varied protocols).
    """
    rng = np.random.default_rng(seed)
    proto = protocol or str(rng.choice(list(PROTOCOL_TO_ID.keys())))

    if lambdas is None:
        decades = rng.uniform(-1.0, 1.0, size=n_modes)
        lambdas = sorted(float(10.0 ** x) for x in decades)
    else:
        lambdas = [float(x) for x in lambdas]
        n_modes = len(lambdas)

    if weights is None:
        if anisotropic:
            weights = rng.uniform(0.3, 2.0, size=(n_modes, dim))
        else:
            weights = rng.uniform(0.3, 2.0, size=n_modes)
    if g_inf is None:
        g_inf = float(rng.choice([0.0, 0.0, 0.0, rng.uniform(0.05, 0.4)]))
    else:
        g_inf = float(g_inf)

    gammadot = make_protocol(proto, n_steps=n_steps, dt=dt, rng=rng, dim=dim)
    kernel = _make_gt_kernel(
        n_modes=n_modes,
        dim=dim,
        anisotropic=anisotropic,
        lambdas=lambdas,
        weights=weights,
        g_inf=g_inf,
    )
    kernel.eval()
    with torch.no_grad():
        gd_t = torch.from_numpy(gammadot).unsqueeze(0)
        stress = kernel(gd_t, dt=dt).squeeze(0).numpy().astype(np.float32)

    if noise_std > 0:
        stress = stress + noise_std * float(np.std(stress) + 1e-6) * rng.standard_normal(
            stress.shape
        ).astype(np.float32)

    theta_lam = np.asarray(lambdas, dtype=np.float32)
    if anisotropic:
        theta_g = np.asarray(weights, dtype=np.float32).reshape(-1)
    else:
        theta_g = np.asarray(weights, dtype=np.float32)

    return {
        "gammadot": gammadot.astype(np.float32),
        "stress": stress.astype(np.float32),
        "dt": np.float32(dt),
        "lambda": theta_lam,
        "G": theta_g,
        "g_inf": np.float32(g_inf),
        "n_modes": int(n_modes),
        "dim": int(dim),
        "anisotropic": bool(anisotropic),
        "protocol": proto,
        "protocol_id": int(PROTOCOL_TO_ID[proto]),
        "seed": int(seed),
    }
